In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import os
import itertools
import numpy as np
import matplotlib.pyplot as plt
import copy
from lmfit import Model
import qutip as qp
from typing import List
from pathlib import Path
from tensor_networks_simulations.mps.states import MPS

In [5]:
psi = MPS.initial_state_f(8)

[array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]])]